-   id: clubhouse-commit-msg-hook
    name: Prefix Clubhouse Story ID
    description: If present in the branch name, this hook prepends the Story ID to the commit message
    entry: hook.sh
    language: script
    always_run: true
    stages: [prepare-commit-msg]
